# Generated by Django 4.1.7 on 2024-02-17 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('customername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.customer')),
            ],
        ),
    ]
